import { CookieOptions } from "express";

export const COOKIE_NAME = {
    CSRF: "csrf",
    REFRESH_TOKEN: "refreshToken",
} as const;

export const cookieOptions = {
    httpOnly: true,
    secure: true,
    sameSite: "none",
} satisfies CookieOptions;

export const STATUS_CODE = {
    OK: 200,
    CREATED: 201,
    ACCEPTED: 202,
    NO_CONTENT: 204,
    PARTIAL_CONTENT: 206,
    MULTIPLE_CHOICES: 300,
    MOVED_PERMANENTLY: 301,
    FOUND: 302,
    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
    PAYMENT_REQUIRED: 402,
    FORBIDDEN: 403,
    NOT_FOUND: 404,
    METHOD_NOT_ALLOWED: 405,
    REQUEST_TIMEOUT: 408,
    CONFLICT: 409,
    GONE: 410,
    UNPROCESSABLE_ENTITY: 422,
    TOO_MANY_REQUESTS: 429,
    INTERNAL_SERVER_ERROR: 500,
    NOT_IMPLEMENTED: 501,
    BAD_GATEWAY: 502,
    SERVICE_UNAVAILABLE: 503,
    GATEWAY_TIMEOUT: 504,
} as const;

export const METADATA_KEYS = {
    AGE: "age",
    ACTIVE_CAMPAIGN: "activeCampaign",
    AGENCY: "agency",
    ASSET: "asset",
    BROADCAST_PARTNER: "broadcastPartner",
    CATEGORY: "category",
    CITY: "city",
    FORMAT: "format",
    GENDER: "gender",
    KEY_MARKETS: "keyMarket",
    LEAGUE: "league",
    LEAGUE_OWNER: "leagueOwner",
    MARKETING_PLATFORM: "marketingPlatform",
    NCCS: "nccs",
    OTT_PARTNER: "ottPartner",
    PARENT_ORG: "parentOrg",
    PERSONALITY_TRAIT: "personalityTrait",
    SPORTS_DEAL_SUMMARY_LEVEL: "sportsDealSummaryLevel",
    SPORTS_DEAL_SUMMARY_STATUS: "sportsDealSummaryStatus",
    SPORTS_DEAL_SUMMARY_TERRITORY: "sportsDealSummaryTerritory",
    SPORTS_DEAL_SUMMARY_TYPE: "sportsDealSummaryType",
    STATE: "state",
    TAGLINE: "tagline",
    TEAM_OWNER: "teamOwner",
    TERTIARY: "tertiary",
    SPORT: "sport",
    TIER: "tier",
    ASSOCIATION_LEVELS: "associationLevel",
    NATIONALITY: "nationality",
    SOCIAL_MEDIA: "socialMedia",
    ATHLETE_STATUS: "athleteStatus",
    BRAND: "brand",
    TEAM: "team",
    ATHLETE: "athlete",
} as const;
