openapi: 3.0.0
info:
  title: Elucide-sports
  description: >-
    A data intensive sports data management and sponsorship decision making
    platform
  version: 1.0.0
servers:
  - url: http://{{elucide-sports-dev-url}}
tags:
  - name: authentication
    description: Authentication Documentation
  - name: league
  - name: athlete
  - name: team
  - name: brand
paths:
  /api/auth/login:
    post:
      tags:
        - authentication
      summary: Login API
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                username: dummy_username
                password: simplepassword
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/auth/register:
    post:
      tags:
        - authentication
      summary: Register
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                firstName: Dummy
                lastName: User
                email: dummy_user@gmail.com
                username: dummy_username
                password: simplepassword
                role: SUPER_ADMIN
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/admin/league:
    get:
      tags:
        - league
      summary: get-all-leagues
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/admin/league/2:
    get:
      tags:
        - league
      summary: get-league-by-id
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/admin/athlete:
    get:
      tags:
        - athlete
      summary: get-all-athletes
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/admin/athlete/2:
    get:
      tags:
        - athlete
      summary: get-athlete-by-id
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/admin/team:
    get:
      tags:
        - team
      summary: get-all-teams
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/admin/team/3:
    get:
      tags:
        - team
      summary: get-team-by-id
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/admin/brand:
    get:
      tags:
        - brand
      summary: get-all-brands
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/admin/brand/5:
    get:
      tags:
        - brand
      summary: get-brand-by-id
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
