import z from "zod";

export const getAllMetadataSchema = z.object({
    age: z.boolean().optional(),
    tier: z.boolean().optional(),
    gender: z.boolean().optional(),
    personalityTrait: z.boolean().optional(),
    state: z.boolean().optional(),
    city: z.boolean().optional(),
    category: z.boolean().optional(),
    maincategory: z.boolean().optional(),
    parentOrg: z.boolean().optional(),
    agency: z.boolean().optional(),
    tagline: z.boolean().optional(),
    activeCampaign: z.boolean().optional(),
    marketingPlatform: z.boolean().optional(),
    nccs: z.boolean().optional(),
    keyMarket: z.boolean().optional(),
    tertiary: z.boolean().optional(),
    league: z.boolean().optional(),
    teamOwner: z.boolean().optional(),
    leagueOwner: z.boolean().optional(),
    format: z.boolean().optional(),
    broadcastPartner: z.boolean().optional(),
    ottPartner: z.boolean().optional(),
    sportsDealSummaryType: z.boolean().optional(),
    sportsDealSummaryLevel: z.boolean().optional(),
    sportsDealSummaryStatus: z.boolean().optional(),
    sportsDealSummaryTerritory: z.boolean().optional(),
    asset: z.boolean().optional(),
    sport: z.boolean().optional(),
    associationLevel: z.boolean().optional(),
    nationality: z.boolean().optional(),
    socialMedia: z.boolean().optional(),
    athleteStatus: z.boolean().optional(),
    brand: z.boolean().optional(),
    athlete: z.boolean().optional(),
    team: z.boolean().optional(),
});

export type TGetAllMetadataSchema = z.infer<typeof getAllMetadataSchema>;
