name: Deploy to EC2

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Copy via SSH and run deploy script
              uses: appleboy/ssh-action@v0.1.6
              with:
                  host: ${{ secrets.EC2_HOST }}
                  username: ${{ secrets.EC2_USER }}
                  key: ${{ secrets.EC2_SECRET }}
                  script: |
                      cd elucide-sports-backend/
                      git restore .
                      git pull origin main --force
                      npm install
                      rm -rf dist/
                      npm run build
                      pm2 restart Elucide --update-env
                      pm2 save
